[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "terminado"
author = "Jupyter Development Team"
author-email = "jupyter@googlegroups.com"
home-page = "https://github.com/jupyter/terminado"
description-file = "README.rst"
requires = [
    "ptyprocess;os_name!='nt'",
    "pywinpty (>=0.5);os_name=='nt'",
    "tornado (>=4)",
]
requires-python=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
classifiers=[
    "Environment :: Web Environment",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 2",
    "Programming Language :: Python :: 3",
    "Topic :: Terminals :: Terminal Emulators/X Terminals",
]
